// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.17.3
// source: modules/lights/lights.proto

package lights

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ZoneState int32

const (
	ZoneState_ON            ZoneState = 0
	ZoneState_OFF           ZoneState = 1
	ZoneState_OFFTIMER      ZoneState = 2
	ZoneState_COLOR         ZoneState = 3
	ZoneState_RANDOMCOLOR   ZoneState = 4
	ZoneState_DIM           ZoneState = 5
	ZoneState_NIGHTVISION   ZoneState = 6
	ZoneState_EVENINGVISION ZoneState = 7
	ZoneState_MORNINGVISION ZoneState = 8
)

// Enum value maps for ZoneState.
var (
	ZoneState_name = map[int32]string{
		0: "ON",
		1: "OFF",
		2: "OFFTIMER",
		3: "COLOR",
		4: "RANDOMCOLOR",
		5: "DIM",
		6: "NIGHTVISION",
		7: "EVENINGVISION",
		8: "MORNINGVISION",
	}
	ZoneState_value = map[string]int32{
		"ON":            0,
		"OFF":           1,
		"OFFTIMER":      2,
		"COLOR":         3,
		"RANDOMCOLOR":   4,
		"DIM":           5,
		"NIGHTVISION":   6,
		"EVENINGVISION": 7,
		"MORNINGVISION": 8,
	}
)

func (x ZoneState) Enum() *ZoneState {
	p := new(ZoneState)
	*p = x
	return p
}

func (x ZoneState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ZoneState) Descriptor() protoreflect.EnumDescriptor {
	return file_modules_lights_lights_proto_enumTypes[0].Descriptor()
}

func (ZoneState) Type() protoreflect.EnumType {
	return &file_modules_lights_lights_proto_enumTypes[0]
}

func (x ZoneState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ZoneState.Descriptor instead.
func (ZoneState) EnumDescriptor() ([]byte, []int) {
	return file_modules_lights_lights_proto_rawDescGZIP(), []int{0}
}

type State struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	On         bool  `protobuf:"varint,1,opt,name=on,proto3" json:"on,omitempty"`
	Brightness int32 `protobuf:"varint,2,opt,name=brightness,proto3" json:"brightness,omitempty"`
}

func (x *State) Reset() {
	*x = State{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_lights_lights_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_modules_lights_lights_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_modules_lights_lights_proto_rawDescGZIP(), []int{0}
}

func (x *State) GetOn() bool {
	if x != nil {
		return x.On
	}
	return false
}

func (x *State) GetBrightness() int32 {
	if x != nil {
		return x.Brightness
	}
	return 0
}

type LightGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type   string  `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id     int32   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Name   string  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	State  *State  `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	Lights []int32 `protobuf:"varint,5,rep,packed,name=lights,proto3" json:"lights,omitempty"`
}

func (x *LightGroup) Reset() {
	*x = LightGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_lights_lights_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LightGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LightGroup) ProtoMessage() {}

func (x *LightGroup) ProtoReflect() protoreflect.Message {
	mi := &file_modules_lights_lights_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LightGroup.ProtoReflect.Descriptor instead.
func (*LightGroup) Descriptor() ([]byte, []int) {
	return file_modules_lights_lights_proto_rawDescGZIP(), []int{1}
}

func (x *LightGroup) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LightGroup) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LightGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LightGroup) GetState() *State {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *LightGroup) GetLights() []int32 {
	if x != nil {
		return x.Lights
	}
	return nil
}

type Light struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id    int32  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Name  string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	State *State `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *Light) Reset() {
	*x = Light{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_lights_lights_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Light) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Light) ProtoMessage() {}

func (x *Light) ProtoReflect() protoreflect.Message {
	mi := &file_modules_lights_lights_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Light.ProtoReflect.Descriptor instead.
func (*Light) Descriptor() ([]byte, []int) {
	return file_modules_lights_lights_proto_rawDescGZIP(), []int{2}
}

func (x *Light) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Light) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Light) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Light) GetState() *State {
	if x != nil {
		return x.State
	}
	return nil
}

type LightGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Color      string    `protobuf:"bytes,2,opt,name=color,proto3" json:"color,omitempty"`
	Colors     []string  `protobuf:"bytes,3,rep,name=colors,proto3" json:"colors,omitempty"`
	Brightness int32     `protobuf:"varint,4,opt,name=brightness,proto3" json:"brightness,omitempty"`
	State      ZoneState `protobuf:"varint,5,opt,name=state,proto3,enum=lights.ZoneState" json:"state,omitempty"`
}

func (x *LightGroupRequest) Reset() {
	*x = LightGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_lights_lights_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LightGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LightGroupRequest) ProtoMessage() {}

func (x *LightGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_modules_lights_lights_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LightGroupRequest.ProtoReflect.Descriptor instead.
func (*LightGroupRequest) Descriptor() ([]byte, []int) {
	return file_modules_lights_lights_proto_rawDescGZIP(), []int{3}
}

func (x *LightGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LightGroupRequest) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *LightGroupRequest) GetColors() []string {
	if x != nil {
		return x.Colors
	}
	return nil
}

func (x *LightGroupRequest) GetBrightness() int32 {
	if x != nil {
		return x.Brightness
	}
	return 0
}

func (x *LightGroupRequest) GetState() ZoneState {
	if x != nil {
		return x.State
	}
	return ZoneState_ON
}

type LightResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lights []*Light      `protobuf:"bytes,1,rep,name=lights,proto3" json:"lights,omitempty"`
	Groups []*LightGroup `protobuf:"bytes,2,rep,name=groups,proto3" json:"groups,omitempty"`
}

func (x *LightResponse) Reset() {
	*x = LightResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_lights_lights_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LightResponse) ProtoMessage() {}

func (x *LightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_modules_lights_lights_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LightResponse.ProtoReflect.Descriptor instead.
func (*LightResponse) Descriptor() ([]byte, []int) {
	return file_modules_lights_lights_proto_rawDescGZIP(), []int{4}
}

func (x *LightResponse) GetLights() []*Light {
	if x != nil {
		return x.Lights
	}
	return nil
}

func (x *LightResponse) GetGroups() []*LightGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

type ZoneStateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Color string `protobuf:"bytes,1,opt,name=color,proto3" json:"color,omitempty"`
}

func (x *ZoneStateResponse) Reset() {
	*x = ZoneStateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_lights_lights_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZoneStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoneStateResponse) ProtoMessage() {}

func (x *ZoneStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_modules_lights_lights_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoneStateResponse.ProtoReflect.Descriptor instead.
func (*ZoneStateResponse) Descriptor() ([]byte, []int) {
	return file_modules_lights_lights_proto_rawDescGZIP(), []int{5}
}

func (x *ZoneStateResponse) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type ZoneStateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	State ZoneState `protobuf:"varint,5,opt,name=state,proto3,enum=lights.ZoneState" json:"state,omitempty"`
}

func (x *ZoneStateRequest) Reset() {
	*x = ZoneStateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_lights_lights_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZoneStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoneStateRequest) ProtoMessage() {}

func (x *ZoneStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_modules_lights_lights_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoneStateRequest.ProtoReflect.Descriptor instead.
func (*ZoneStateRequest) Descriptor() ([]byte, []int) {
	return file_modules_lights_lights_proto_rawDescGZIP(), []int{6}
}

func (x *ZoneStateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ZoneStateRequest) GetState() ZoneState {
	if x != nil {
		return x.State
	}
	return ZoneState_ON
}

var File_modules_lights_lights_proto protoreflect.FileDescriptor

var file_modules_lights_lights_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x2f, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73,
	0x2f, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6c,
	0x69, 0x67, 0x68, 0x74, 0x73, 0x22, 0x37, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6e, 0x12, 0x1e,
	0x0a, 0x0a, 0x62, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x62, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x22, 0x81,
	0x01, 0x0a, 0x0a, 0x4c, 0x69, 0x67, 0x68, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x69,
	0x67, 0x68, 0x74, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x05, 0x52, 0x06, 0x6c, 0x69, 0x67, 0x68,
	0x74, 0x73, 0x22, 0x64, 0x0a, 0x05, 0x4c, 0x69, 0x67, 0x68, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x9e, 0x01, 0x0a, 0x11, 0x4c, 0x69, 0x67,
	0x68, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6c, 0x6f,
	0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x73,
	0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x62, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73,
	0x12, 0x27, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x11, 0x2e, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x2e, 0x5a, 0x6f, 0x6e, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x62, 0x0a, 0x0d, 0x4c, 0x69, 0x67,
	0x68, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x06, 0x6c, 0x69,
	0x67, 0x68, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6c, 0x69, 0x67,
	0x68, 0x74, 0x73, 0x2e, 0x4c, 0x69, 0x67, 0x68, 0x74, 0x52, 0x06, 0x6c, 0x69, 0x67, 0x68, 0x74,
	0x73, 0x12, 0x2a, 0x0a, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x2e, 0x4c, 0x69, 0x67, 0x68, 0x74,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x22, 0x29, 0x0a,
	0x11, 0x5a, 0x6f, 0x6e, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x22, 0x4f, 0x0a, 0x10, 0x5a, 0x6f, 0x6e, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x27, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x11, 0x2e, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x2e, 0x5a, 0x6f, 0x6e, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2a, 0x86, 0x01, 0x0a, 0x09, 0x5a, 0x6f,
	0x6e, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4e, 0x10, 0x00, 0x12,
	0x07, 0x0a, 0x03, 0x4f, 0x46, 0x46, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x4f, 0x46, 0x46, 0x54,
	0x49, 0x4d, 0x45, 0x52, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x43, 0x4f, 0x4c, 0x4f, 0x52, 0x10,
	0x03, 0x12, 0x0f, 0x0a, 0x0b, 0x52, 0x41, 0x4e, 0x44, 0x4f, 0x4d, 0x43, 0x4f, 0x4c, 0x4f, 0x52,
	0x10, 0x04, 0x12, 0x07, 0x0a, 0x03, 0x44, 0x49, 0x4d, 0x10, 0x05, 0x12, 0x0f, 0x0a, 0x0b, 0x4e,
	0x49, 0x47, 0x48, 0x54, 0x56, 0x49, 0x53, 0x49, 0x4f, 0x4e, 0x10, 0x06, 0x12, 0x11, 0x0a, 0x0d,
	0x45, 0x56, 0x45, 0x4e, 0x49, 0x4e, 0x47, 0x56, 0x49, 0x53, 0x49, 0x4f, 0x4e, 0x10, 0x07, 0x12,
	0x11, 0x0a, 0x0d, 0x4d, 0x4f, 0x52, 0x4e, 0x49, 0x4e, 0x47, 0x56, 0x49, 0x53, 0x49, 0x4f, 0x4e,
	0x10, 0x08, 0x32, 0xc0, 0x01, 0x0a, 0x06, 0x4c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x12, 0x39, 0x0a,
	0x05, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x12, 0x19, 0x2e, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x2e,
	0x4c, 0x69, 0x67, 0x68, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x15, 0x2e, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x2e, 0x4c, 0x69, 0x67, 0x68, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x06, 0x54, 0x6f, 0x67, 0x67,
	0x6c, 0x65, 0x12, 0x19, 0x2e, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x2e, 0x4c, 0x69, 0x67, 0x68,
	0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e,
	0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x2e, 0x4c, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x08, 0x53, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x12, 0x18, 0x2e, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x2e, 0x5a, 0x6f, 0x6e, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x6c, 0x69, 0x67,
	0x68, 0x74, 0x73, 0x2e, 0x5a, 0x6f, 0x6e, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x11, 0x5a, 0x0f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2f, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_modules_lights_lights_proto_rawDescOnce sync.Once
	file_modules_lights_lights_proto_rawDescData = file_modules_lights_lights_proto_rawDesc
)

func file_modules_lights_lights_proto_rawDescGZIP() []byte {
	file_modules_lights_lights_proto_rawDescOnce.Do(func() {
		file_modules_lights_lights_proto_rawDescData = protoimpl.X.CompressGZIP(file_modules_lights_lights_proto_rawDescData)
	})
	return file_modules_lights_lights_proto_rawDescData
}

var file_modules_lights_lights_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_modules_lights_lights_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_modules_lights_lights_proto_goTypes = []interface{}{
	(ZoneState)(0),            // 0: lights.ZoneState
	(*State)(nil),             // 1: lights.State
	(*LightGroup)(nil),        // 2: lights.LightGroup
	(*Light)(nil),             // 3: lights.Light
	(*LightGroupRequest)(nil), // 4: lights.LightGroupRequest
	(*LightResponse)(nil),     // 5: lights.LightResponse
	(*ZoneStateResponse)(nil), // 6: lights.ZoneStateResponse
	(*ZoneStateRequest)(nil),  // 7: lights.ZoneStateRequest
}
var file_modules_lights_lights_proto_depIdxs = []int32{
	1, // 0: lights.LightGroup.state:type_name -> lights.State
	1, // 1: lights.Light.state:type_name -> lights.State
	0, // 2: lights.LightGroupRequest.state:type_name -> lights.ZoneState
	3, // 3: lights.LightResponse.lights:type_name -> lights.Light
	2, // 4: lights.LightResponse.groups:type_name -> lights.LightGroup
	0, // 5: lights.ZoneStateRequest.state:type_name -> lights.ZoneState
	4, // 6: lights.Lights.Alert:input_type -> lights.LightGroupRequest
	4, // 7: lights.Lights.Toggle:input_type -> lights.LightGroupRequest
	7, // 8: lights.Lights.SetState:input_type -> lights.ZoneStateRequest
	5, // 9: lights.Lights.Alert:output_type -> lights.LightResponse
	5, // 10: lights.Lights.Toggle:output_type -> lights.LightResponse
	6, // 11: lights.Lights.SetState:output_type -> lights.ZoneStateResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_modules_lights_lights_proto_init() }
func file_modules_lights_lights_proto_init() {
	if File_modules_lights_lights_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_modules_lights_lights_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*State); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_lights_lights_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LightGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_lights_lights_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Light); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_lights_lights_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LightGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_lights_lights_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LightResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_lights_lights_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZoneStateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_lights_lights_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZoneStateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_modules_lights_lights_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_modules_lights_lights_proto_goTypes,
		DependencyIndexes: file_modules_lights_lights_proto_depIdxs,
		EnumInfos:         file_modules_lights_lights_proto_enumTypes,
		MessageInfos:      file_modules_lights_lights_proto_msgTypes,
	}.Build()
	File_modules_lights_lights_proto = out.File
	file_modules_lights_lights_proto_rawDesc = nil
	file_modules_lights_lights_proto_goTypes = nil
	file_modules_lights_lights_proto_depIdxs = nil
}
